[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#030712"
secondaryBackgroundColor = "#0f172a"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
